package app.rcq.android.model

/**
 * One Radio chat message — Android port of the iOS `RadioMessage`. Ephemeral:
 * lives only in [app.rcq.android.nearby.RadioController]'s in-memory list,
 * never written to MessageDb (a Radio session leaves no trace at rest).
 * Trimmed payload: text + optional reply + reactions, no media.
 */
data class RadioMessage(
    val id: String,                       // UUID — generated by sender
    val senderDisplayName: String,        // anonymous label inside the session
    val isFromMe: Boolean,
    val text: String,
    val timestampMs: Long,
    val replyToId: String? = null,
    val replyToSender: String? = null,
    val replyToBody: String? = null,
    /** `reactor display name -> asset name`. One reaction per name. */
    val reactions: Map<String, String> = emptyMap(),
)
